name: tests_example
description: "A new Flutter project. Created by Slidy"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

scripts:
  mobx: flutter clean & flutter pub get & flutter pub run build_runner build --delete-conflicting-outputs  

dependencies:
  open_file: ^3.0.1
  url_launcher: ^5.4.2
  font_awesome_flutter: ^8.8.1
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  dio: ^3.0.9
  rxdart:
  flutter_modular: ^1.1.2
  json_annotation: ^3.0.1
  hive: ^1.4.1+1
  path_provider: ^1.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/mocks/months.json
      - assets/mocks/payroll.json
      - assets/mocks/login.json